# -*- coding: utf-8 -*-
[pytest]
pythonpath = .
qt_api = pyside6
testpaths = tests
addopts = -v --timeout=30
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    qml: marks QML-related tests
