# -*- coding: utf-8 -*-
"""应用常量"""

# ── 窗口 ──
WIN_WIDTH = 960
WIN_HEIGHT = 680
MIN_WIDTH = 800
MIN_HEIGHT = 550

# ── 相位 ──
PHASE_IDLE = "idle"
PHASE_RUNNING = "running"
PHASE_PAUSED = "paused"
PHASE_DONE = "done"

# ── 配色（微信风格） ──
COLOR_PRIMARY = "#07c160"
COLOR_PRIMARY_HOVER = "#06ad56"
COLOR_PRIMARY_PRESS = "#059a4c"
COLOR_BUBBLE_BG = "#95ec69"
COLOR_BUBBLE_FG = "#000000"
COLOR_FILE_CARD_BG = "#f5f5f5"
COLOR_LOG_OK = "#2e7d32"
COLOR_LOG_ERR = "#c62828"
COLOR_TEXT_PRIMARY = "#191919"
COLOR_TEXT_SECONDARY = "#666666"
COLOR_TEXT_HINT = "#999999"
COLOR_BG_PRIMARY = "#ffffff"
COLOR_BG_SECONDARY = "#f7f7f7"
COLOR_BORDER = "#e5e5e5"
COLOR_DIVIDER = "#ededed"
COLOR_WARNING_BG = "#fff3e0"
COLOR_TOOLTIP_BG = "#ffffe0"
COLOR_DANGER = "#d9534f"
COLOR_DANGER_HOVER = "#c9302c"

# ── 字体 ──
FONT_FAMILY = "Microsoft YaHei"
FONT_FAMILY_LOG = "Consolas, Cascadia Code, monospace"
FONT_SIZE_NORMAL = 13
FONT_SIZE_SMALL = 12
FONT_SIZE_TINY = 11
FONT_SIZE_LOG = 12

# ── 圆角 ──
RADIUS_SMALL = 4
RADIUS_MEDIUM = 6
RADIUS_LARGE = 8

# ── 间距 ──
SPACING_TINY = 4
SPACING_SMALL = 8
SPACING_MEDIUM = 12
SPACING_LARGE = 16
